# Generated by Django 4.2.1 on 2023-05-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='taken_EECS110',
            new_name='EECS110',
        ),
    ]
