# Generated by Django 4.2.1 on 2023-05-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_taken_eecs110_student_eecs110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='EECS110',
            new_name='taken_EECS110',
        ),
    ]
