# Generated by Django 4.2.1 on 2023-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_eecs110_student_taken_eecs110'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='taken_EECS183',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS200',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS201',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS203',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS215',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS216',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS230',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS270',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS280',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS281',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS298',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS300',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS301',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS311',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS312',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS314',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS320',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS330',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS334',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS351',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS370',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS373',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS376',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS388',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS399',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS402',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS409',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS411',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS413',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS414',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS421',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS423',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS427',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS428',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS434',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS435',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS441',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS442',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS443',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS445',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS452',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS453',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS455',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS458',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS460',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS461',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS463',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS464',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS465',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS467',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS470',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS471',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS473',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS475',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS477',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS482',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS483',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS484',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS485',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS487',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS489',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS490',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS491',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS492',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS494',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS495',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS496',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS497',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS498',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS499',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS501',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS507',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS517',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS520',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS523',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS530',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS540',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS542',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS544',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS551',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS553',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS554',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS558',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS560',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS561',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS563',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS564',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS574',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS575',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS582',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS584',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS587',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS595',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS598',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS599',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='taken_EECS628',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
