# Generated by Django 4.2.1 on 2023-05-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_student_taken_eecs183_student_taken_eecs200_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.TextField(blank=True, default='')),
            ],
        ),
    ]
