# Generated by Django 4.2.1 on 2023-05-15 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0006_searchrequest_user_alter_searchrequest_user_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='user',
            field=models.OneToOneField(default='NONE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
